SUBMIT_BASE_DIR = "NSHRUNNER_SUBMIT_BASE_DIR"
JOB_INDEX = "NSHRUNNER_JOB_INDEX"
TIMEOUT_SIGNAL = "NSHRUNNER_TIMEOUT_SIGNAL"
PREEMPT_SIGNAL = "NSHRUNNER_PREEMPT_SIGNAL"
LOCAL_RANK = "NSHRUNNER_LOCAL_RANK"
GLOBAL_RANK = "NSHRUNNER_GLOBAL_RANK"


LSF_EXIT_SCRIPT_DIR = "NSHRUNNER_LSF_EXIT_SCRIPT_DIR"
