from __future__ import annotations

SESSION_ID = "NSHRUNNER_SESSION_ID"
SESSION_DIR = "NSHRUNNER_SESSION_DIR"
SNAPSHOT_DIR = "NSHRUNNER_SNAPSHOT_DIR"
SNAPSHOT_MODULES = "NSHRUNNER_SNAPSHOT_MODULES"
IS_WORKER_SCRIPT = "NSHRUNNER_IS_WORKER_SCRIPT"

SUBMIT_BASE_DIR = "NSHRUNNER_SUBMIT_BASE_DIR"
SUBMIT_JOB_INDEX = "NSHRUNNER_SUBMIT_JOB_INDEX"
SUBMIT_TIMEOUT_SIGNAL = "NSHRUNNER_SUBMIT_TIMEOUT_SIGNAL"
SUBMIT_PREEMPT_SIGNAL = "NSHRUNNER_SUBMIT_PREEMPT_SIGNAL"
SUBMIT_LOCAL_RANK = "NSHRUNNER_SUBMIT_LOCAL_RANK"
SUBMIT_GLOBAL_RANK = "NSHRUNNER_SUBMIT_GLOBAL_RANK"
SUBMIT_WORLD_SIZE = "NSHRUNNER_SUBMIT_WORLD_SIZE"
EXIT_SCRIPT_DIR = "NSHRUNNER_SUBMIT_EXIT_SCRIPT_DIR"
SUBMIT_INTERFACE_MODULE = "NSHRUNNER_SUBMIT_INTERFACE_MODULE"
