SNAPSHOT_DIR = "NSHRUNNER_SNAPSHOT_DIR"
SNAPSHOT_MODULES = "NSHRUNNER_SNAPSHOT_MODULES"

SUBMIT_BASE_DIR = "NSHRUNNER_SUBMIT_BASE_DIR"
JOB_INDEX = "NSHRUNNER_SUBMIT_JOB_INDEX"
TIMEOUT_SIGNAL = "NSHRUNNER_SUBMIT_TIMEOUT_SIGNAL"
PREEMPT_SIGNAL = "NSHRUNNER_SUBMIT_PREEMPT_SIGNAL"
LOCAL_RANK = "NSHRUNNER_SUBMIT_LOCAL_RANK"
GLOBAL_RANK = "NSHRUNNER_SUBMIT_GLOBAL_RANK"
WORLD_SIZE = "NSHRUNNER_SUBMIT_WORLD_SIZE"
IS_WORKER_SCRIPT = "NSHRUNNER_SUBMIT_IS_WORKER_SCRIPT"

LSF_EXIT_SCRIPT_DIR = "NSHRUNNER_SUBMIT_LSF_EXIT_SCRIPT_DIR"
